language: python

os:
  - linux

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - python-setuptools

install:
  - pip install --upgrade pip

script:
  python setup.py test
